export const SUCCESS_REPORT = 'SUCCESS_REPORT'
export const FAILTURE_REPORT = 'FAILTURE_REPORT'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const SHOW_CONFIRM = 'SHOW_CONFIRM'

export const LOAD_SUCCESS_REPORT = 'LOAD_SUCCESS_REPORT'
export const LOAD_FAILTURE_REPORT = 'LOAD_FAILTURE_REPORT'

export const SUCCESS_DELETE_REPORT = 'SUCCESS_DELETE_REPORT'
export const FAILTURE_DELETE_REPORT = 'FAILTURE_DELETE_REPORT'

